### ISSUE TITLE
Index out of range errors on renaming sectors to USEEIO names

### ISSUE THREAD

**Issue by WesIngwersen** [USEPA/USEEIO#2]
INFO Renaming sectors to USEEIO names in satellite tables...
Traceback (most recent call last):
  File "useeiopyExample.py", line 9, in <module>
    useeio1pt1 = useeiopy.assemble("USEEIOv1.1")
  File "c:\users\wingwers\useeio-public-test-jun7\useeiopy\__init__.py", line 63, in assemble
    Satellite.renameSatelliteSectors(satcsvfiles, sattablepath)
  File "c:\users\wingwers\useeio-public-test-jun7\useeiopy\Satellite.py", line 61, in renameSatelliteSectors
    names = read_names(Crosswalkrelpath + '/MasterCrosswalk.csv')
  File "c:\users\wingwers\useeio-public-test-jun7\useeiopy\Satellite.py", line 78, in read_names
    names[row[6].strip()] = row[8].strip()
IndexError: list index out of range

**Comment by WesIngwersen** [comment]
An update to the MasterCrosswalk in Excel and resaving caused a formatting issue. Reset the history to remove the commit causing the problem.
